#!/usr/bin/perl

&make_arin;
&make_ripe;
&make_apnic;

sub make_arin() {

	open (F1, "wget -q -O - ftp://ftp.arin.net/netinfo/asn.txt |");
	open (F2, "> as-arin.txt");

	print F2 <<EOT;
#
# This file is generated automatically from
# ftp://ftp.arin.net/netinfo/asn.txt
#
# Do not edit this file
#
EOT

	while (<F1>) {
		chop;
		next if (/ APNIC-AS-\d+-BLOCK /);
		next if (/ RIPE-ASNBLOCK\d+ /);
		next if (/ ASNBLK-RIPE /);
		next if (/ ASNBLK-RIPE-NCC /);
		next if (/ ASN-BLKRIPE\d+ /);
		if (/^  ([\d\-]+)\s+(\S+)\s/) {
			my $autnum = $1;
			my $descr = $2;
			if ($autnum =~ /^(\d+)-(\d+)$/) {
				for (my $i = $1; $i <= $2; $i++) {
					printf(F2 "%5d\tARIN:%s\n", $i, $descr);
				}
			} else {
				printf(F2 "%5d\tARIN:%s\n", $autnum, $descr);
			}
		} else {
			next;
		}
	}

	close F2;
	close F1;
}


sub make_ripe() {

	open (F1, "wget -q -O - ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.aut-num.gz | gunzip |");

	my $autnum = "";
	my $descr;

	my @asnums;

	while (<F1>) {
		chop;
		if (/^aut-num:\s+[Aa][Ss](\d+)$/) {
			$autnum = $1;
			next;
		} elsif (/^as-name:\s+(.*)$/) {
			next if ($1 eq "UNSPECIFIED");
			$descr = $1;
		} elsif (/^descr:\s+(.*\w.*)$/) {
			next if ($autnum eq "");
			$descr = $1;
		} else {
			next;
		}

		if ($autnum ne "") {
			$asnum[$autnum] = $descr;
			$autnum = "";
			$descr = "";
		} else {
			print STDERR "missing aut-num for as-name [$1] in line $.\n";
		}
	}

	close F1;

	open (F2, "> as-ripe.txt");

	print F2 <<EOT;
#
# This file is generated automatically from
# ftp://ftp.ripe.net/ripe/dbase/split/ripe.db.aut-num.gz
#
# Do not edit this file
#
EOT

	for (my $i = 1; $i < 65536; $i++) {
		printf(F2 "%5d\tRIPE:%s\n", $i, $asnum[$i]) if ($asnum[$i] ne "");
	}

	close F2;
}


sub make_apnic() {

	open (F1, "wget -q -O - ftp://ftp.apnic.net/pub/apnic/dbase/data/apnic.an.gz | gunzip |");

	my $autnum = "";
	my $descr;

	my @asnums;

	while (<F1>) {
		chop;
		if (/^\*(an|XX):\s+[Aa][Ss](\d+)$/) {
			$autnum = $2;
			next;
		} elsif (/^\*aa:\s+(.*)$/) {
			next if ($1 eq "UNSPECIFIED");
			$descr = $1;
		} elsif (/^\*de:\s+(.*\w.*)$/) {
			next if ($autnum eq "");
			$descr = $1;
		} else {
			next;
		}

		if ($autnum ne "") {
			if (($descr ne "JPNIC-ASBLOCK-AP") &&
			    ($descr ne "JPNIC-JP-ASN-BLOCK") &&
			    ($descr ne "JPNIC-NET-JP-AS-BLOCK") &&
			    ($descr ne "JPNIC") &&
			    ($descr !~ /^CNNIC-AS-BLOCK/) &&
			    ($descr ne "KRNIC-ASBLOCK-AP") &&
			    ($descr ne "KRNIC")) {
				$asnum[$autnum] = $descr;
			}
			$autnum = "";
			$descr = "";
		} else {
			print STDERR "missing aut-num for as-name [$1] in line $.\n";
		}
	}

	close F1;

	open (F2, "> as-apnic.txt");

	print F2 <<EOT;
#
# This file is generated automatically from
# ftp://ftp.apnic.net/pub/apnic/dbase/data/apnic.an.gz
#
# Do not edit this file
#
EOT

	for (my $i = 1; $i < 65536; $i++) {
		printf(F2 "%5d\tAPNIC:%s\n", $i, $asnum[$i]) if ($asnum[$i] ne "");
	}

	close F2;
}
